version: 2

jobs:
    build-website:
          resource_class: medium+
          docker:
              - image: nikolaik/python-nodejs:python3.7-nodejs8
          working_directory: ~/repo
          steps:
              - restore_cache:
                    keys:
                        - repo-{{ .Environment.CIRCLE_SHA1 }}
              - run: yarn build:prod
              - save_cache:
                    key: repo-{{ .Environment.CIRCLE_SHA1 }}
                    paths:
                        - ~/repo
    
workflows:
    version: 2
    main:
        jobs:
            - build-website
