version: 2

jobs:
    build-website:
          resource_class: medium+
          docker:
              - image: nikolaik/python-nodejs:python3.7-nodejs8
          working_directory: ~/repo
          steps:
              - checkout
              - run:
                  name: install-yarn
                  command: npm install --global --force yarn@1.17.0
              - run:
                  name: yarn
                  command: yarn --frozen-lockfile --ignore-engines install || yarn --frozen-lockfile --ignore-engines install
              - run:
                  name: run unit tests
                  command: yarn test
              - run: yarn build:prod
              - save_cache:
                    key: repo-{{ .Environment.CIRCLE_SHA1 }}
                    paths:
                        - ~/repo
    
workflows:
    version: 2
    main:
        jobs:
            - build-website
